<<<<<<< HEAD
# Generated by Django 3.1.2 on 2022-02-06 23:36
=======
# Generated by Django 3.1.2 on 2021-12-20 12:42
>>>>>>> 20c4626fc12bc2d60e4ce664a1c1047ff7ee1646

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Translation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=1000)),
<<<<<<< HEAD
                ('braille_translation', models.CharField(blank=True, max_length=3000)),
=======
                ('braille_translation', models.CharField(max_length=3000)),
>>>>>>> 20c4626fc12bc2d60e4ce664a1c1047ff7ee1646
            ],
        ),
    ]
